name = "snowflare"
main = "src/index.ts"
compatibility_date = "2024-12-18"

compatibility_flags = [ "nodejs_compat" ]

[durable_objects]
bindings = [
  { class_name = "Relay", name = "RELAY" },
  { class_name = "Register", name = "REGISTER" }
]

[[migrations]]
new_classes = ["Relay"]
tag = "v1"

[[migrations]]
new_classes = ["Register"]
tag = "v2"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1
