name = "snowflare"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public/"

[[migrations]]
new_classes = ["Relay"]
tag = "v1"

[[migrations]]
deleted_classes = ["Relay"]
tag = "v2"

[[kv_namespaces]]
binding = "events"
id = "%KV_ID_EVENTS%"

[[kv_namespaces]]
binding = "accounts"
id = "%KV_ID_ACCOUNTS%"

[[d1_databases]]
binding = "DB"
database_name = "snowflare-events"
database_id = "%DB_ID%"

[observability]
enabled = true
head_sampling_rate = 1
