name = "snowflare"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public/"

[durable_objects]
bindings = [
  { class_name = "Relay", name = "RELAY" },
  { class_name = "Register", name = "REGISTER" }
]

[[migrations]]
new_classes = ["Relay"]
tag = "v1"

[[migrations]]
new_classes = ["Register"]
tag = "v2"

[[kv_namespaces]]
binding = "events"
id = "%KV_ID%"

[[d1_databases]]
binding = "DB"
database_name = "snowflare-events"
database_id = "%DB_ID%"

[observability]
enabled = true
head_sampling_rate = 1
